# Dockerfile
FROM postgres:latest

# Set default environment variables
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB BrainAgriculture

# Expose PostgreSQL default port
EXPOSE 5432